server:
  port: 5004
spring:
  cloud:
    config:
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/jfabiant/microservicios-tutorial-1
          search-paths: config-data
  application:
    name: config-service